### ISSUE TITLE
Can we use flubber to animate from svg shape to path

### ISSUE THREAD

**Issue by Jatinbalodhi96** [veltman/flubber#103]
Can we use flubber to animate from SVG shape (like rect, circle) to path?
If it is possible can someone share an example or code snippet rearging that.

Or is there some way to animate many circle to topojson map?

Thanks

**Comment by veltman** [comment]
Yes, you can either use the `toCircle`/`fromCircle` and `toRect`/`fromRect` methods (see the README), or if you have an svg `<circle>` or `<rect>` element, you can first convert it to the `<path>` equivalent before animating.

[Pathologist](https://gitlab.com/Rich-Harris/pathologist) will do this conversion for you.
