### ISSUE TITLE
Broken in latest Chromium

### ISSUE THREAD

**Issue by amadeus** [veltman/flubber#109]
It looks like this library is now broken in the latest version of Chromium. Apparently they've conformed to the spec. To repro the issue, simply check out this example in the latest [Chromium](https://download-chromium.appspot.com/):

https://veltman.github.io/flubber/demos/basic-svg.html

```
Uncaught DOMException: Failed to execute 'getPointAtLength' on 'SVGGeometryElement': The element is in an inactive document.
```

Looks like the source of the problem is that we can no longer call https://github.com/veltman/flubber/blob/0cadadf3eb15cd5b2ec7c45c70601ff88b76a6c3/src/svg.js#L84 from the output of here: https://github.com/veltman/flubber/blob/0cadadf3eb15cd5b2ec7c45c70601ff88b76a6c3/src/svg.js#L94-L108

There's a related Chromium issue - https://bugs.chromium.org/p/chromium/issues/detail?id=1108966

**Comment by veltman** [comment]
👀 Looking into this

**Comment by veltman** [comment]
@amadeus catching up on the thread and it looks like the initial change wasn't actually necessary to conform to the spec and they partially reverted it - can you confirm whether this is still an issue for you? It seems to work in the latest Chrome Canary (86.0.4226.0).

**Comment by amadeus** [comment]
Yeah - looks like they just reverted the offending stuff, but I guess there's still a question whether they will re-introduce it in M-87. I see you're posting there as well.

**Comment by veltman** [comment]
Per that thread it seems like this is resolved so will close this but will think about defensive changes to make against a future similar update. Thanks for flagging!
