### ISSUE TITLE
Limiting the size of the package as published to & installed from NPM-style registries

### ISSUE THREAD

**Issue by jameswomack** [veltman/flubber#5]
Hi Noah, thanks for releasing this. Very useful.

AFAICT, everything in the git repo is published to NPM, and yet the bulk of it is (again AFAICT) not needed. I would introduce an .npmignore or [files](https://docs.npmjs.com/files/package.json#files) array to take care of this.

Does that make sense or am I missing something?

**Comment by veltman** [comment]
Thanks for the note, removed the demos and tests.

**Comment by marlazinger200** [comment]
1
