### ISSUE TITLE
Can be get code from this project?

### ISSUE THREAD

**Issue by dalisoft** [veltman/flubber#8]
Hello @veltman, amazing job, seems works fine in most case.

I've made svg-morphing and other tools 2-year ago which based on snapsvg and d3.js (path tween demo), then amazing @colinmeinke made the wilderness.js, i replaced code with wilderness.js and second demo still d3.js and now seem i can change second way with this way, my project was closed-source due of more peoples told like i stole code from gsap morphsvg, and removed from github. name has been unim.js, superanimation.js, sajs, etc...

I will credit project in comments of js, whenever i am use. I have all of code including moveIndex (wilderness.js), just using `add` and `normalise` for get better result. Thanks for work.

I'd like to simplify the code as has much unnecessary dependecies that can be with simply code or other small deps, your morphing looks nice and best because there has `pieceOrder` function that does the job nice and orders everything in right and fast.

**Comment by veltman** [comment]
I'm not sure I totally understand the question - you're welcome to use the code in compliance with the license:

https://github.com/veltman/flubber/blob/master/LICENSE

Please don't just copy chunks of it into your own code.

**Comment by dalisoft** [comment]
Thanks
