### ISSUE TITLE
flubber with greensock

### ISSUE THREAD

**Issue by MartDSam** [veltman/flubber#98]
Do you have any examples of how to use this plugin along with greensock?

**Comment by OSUblake** [comment]
https://greensock.com/forums/topic/19033-tweenmax-flubberjs-or-other-svg-morph-library/

**Comment by veltman** [comment]
Thanks @OSUblake!

**Comment by MartDSam** [comment]
hahahahaha @OSUblake Thank you. I had forgotten my question here, sorry.
